{% set version = "1.1.19" %}

package:
  name: moto
  version: {{ version }}

source:
  fn: moto-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/m/moto/moto-{{ version }}.tar.gz
  sha256: 3657fa0b44a5a4e41be7613aa648ca5e5b7e79a422d6c2e380272a8923a22fcc

build:
  number: 0
  entry_points:
    - moto_server = moto.server:main
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - jinja2 >=2.8
    - cryptography >=2.0.0
    - boto >=2.36.0
    - boto3 >=1.2.1
    - cookies
    - requests >=2.5
    - xmltodict
    - dicttoxml
    - six>1.9
    - werkzeug
    - pyaml
    - pytz
    - python-dateutil
    - mock
    - flask

  run:
    - python
    - jinja2 >=2.8
    - cryptography >=2.0.0
    - boto >=2.36.0
    - boto3 >=1.2.1
    - cookies
    - requests >=2.5
    - xmltodict
    - dicttoxml
    - six>1.9
    - werkzeug
    - pyaml
    - pytz
    - python-dateutil
    - mock
    - flask

test:
  imports:
    - moto

  commands:
    - moto_server --help

about:
  home: http://getmoto.org
  license: Apache-2.0
  summary: A library that allows your python tests to easily mock out the boto library.
  license_family: APACHE
  license_file: LICENSE
  doc_url: http://docs.getmoto.org
  dev_url: https://github.com/spulec/moto

extra:
  recipe-maintainers:
    - johanneskoester
