{% set version = "1.3.14" %}

package:
  name: moto
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/m/moto/moto-{{ version }}.tar.gz
    sha256: 79aeaeed1592a24d3c488840065a3fcb3f4fa7ba40259e112482454c0e48a03a
  - url: https://github.com/spulec/moto/archive/{{ version }}.tar.gz
    sha256: e10412aa495af0f254d3944fd369e75a7c1bcc2f6940a7ea0a0cea34b2f8bf27
    folder: github

build:
  number: 0
  noarch: python
  entry_points:
    - moto_server = moto.server:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - jinja2 >=2.10.1
    - boto >=2.36.0
    # we need to bound this since 198 changed some of the api
    - boto3 >=1.9.201
    - botocore >=1.12.201
    - cryptography >=2.3.0
    - requests >=2.5
    - xmltodict
    - six >1.9
    - werkzeug
    - pyyaml >=5.1
    - pytz
    - python-dateutil >=2.1,<3.0.0
    - python-jose <4.0.0
    - mock
    - docker-py >=2.5.1
    - jsondiff 1.1.2
    - aws-xray-sdk !=0.96,>=0.93
    - responses >=0.9.0
    - idna >=2.5,<2.9
    - cfn-lint >=0.4.0
    - sshpubkeys >=3.1.0,<4.0
    - flask
    # this is an undeclared dependency!
    - backports.tempfile

test:
  imports:
    - moto
    - moto.acm
    - moto.apigateway
    - moto.autoscaling
    - moto.awslambda
    - moto.batch
    - moto.cloudformation
    - moto.cloudwatch
    - moto.cognitoidentity
    - moto.cognitoidp
    - moto.config
    - moto.core
    - moto.datapipeline
    - moto.dynamodb
    - moto.dynamodb2
    - moto.dynamodbstreams
    - moto.ec2
    - moto.ec2.responses
    - moto.ecr
    - moto.ecs
    - moto.elb
    - moto.elbv2
    - moto.emr
    - moto.events
    - moto.glacier
    - moto.glue
    - moto.iam
    - moto.instance_metadata
    - moto.iot
    - moto.iotdata
    - moto.kinesis
    - moto.kms
    - moto.logs
    - moto.opsworks
    - moto.organizations
    - moto.packages
    - moto.packages.httpretty
    - moto.polly
    - moto.rds
    - moto.rds2
    - moto.redshift
    - moto.resourcegroupstaggingapi
    - moto.route53
    - moto.s3
    - moto.s3bucket_path
    - moto.secretsmanager
    - moto.ses
    - moto.sns
    - moto.sqs
    - moto.ssm
    - moto.sts
    - moto.swf
    - moto.swf.models
    - moto.xray
  requires:
    - nose
    - nose-exclude
    - pytest
    - pip
    - freezegun
    - parameterized
  source_files:
    - github/tests
  commands:
    - moto_server --help
    - pip install sure
    - cd github
    - >
        nosetests tests 
        --exclude-test=test_lambda.test_invoke_requestresponse_function
        --exclude-test=test_cognitoidp.test_token_legitimacy
        --exclude-test=test_lambda.test_invoke_function_from_dynamodb
        --exclude-test=test_lambda.test_invoke_function_from_sns
        --exclude-test=test_lambda.test_invoke_function_from_sqs
        --exclude-test=test_lambda.test_invoke_function_from_sqs_exception

about:
  home: http://getmoto.org
  license: Apache-2.0
  summary: A library that allows your python tests to easily mock out the boto library.
  license_family: APACHE
  license_file: LICENSE
  doc_url: http://docs.getmoto.org
  dev_url: https://github.com/spulec/moto

extra:
  recipe-maintainers:
    - johanneskoester
    - mariusvniekerk
    - hajapy
