{% set version = "5.0.22" %}

package:
  name: moto
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/m/moto/moto-{{ version }}.tar.gz
    sha256: daf47b8a1f5f190cd3eaa40018a643f38e542277900cf1db7f252cedbfed998f
  - url: https://github.com/spulec/moto/archive/{{ version }}.tar.gz
    sha256: e4484140e47840182bb388d0a79855bc606617ec7128054229241ae662298dea
    folder: github

build:
  number: 1
  noarch: python
  entry_points:
    - moto_server = moto.server:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
    - setuptools
  run:
    # dependencies from grayskull
    - python >={{ python_min }}
    - boto3 >=1.9.201
    - botocore >=1.14.0,!=1.35.45,!=1.35.46
    - cryptography >=3.3.1
    - requests >=2.5
    - xmltodict
    - werkzeug >=0.5,!=2.2.0,!=2.2.1
    - python-dateutil <3.0.0,>=2.1
    - responses >=0.15.0
    - jinja2 >=2.10.1
    # dependencies for test imports
    - openapi-spec-validator >=0.6.0
    - joserfc
    - pyparsing >=3.0.7
    - jsondiff >=1.1.2
    - aws-xray-sdk !=0.96,>=0.93
    - flask !=2.2.0,!=2.2.1
    - flask-cors

test:
  imports:
    - moto
    - moto.acm
    - moto.apigateway
    - moto.applicationautoscaling
    - moto.appsync
    - moto.athena
    - moto.autoscaling
    - moto.awslambda
    - moto.batch
    - moto.budgets
    - moto.cloudformation
    - moto.cloudfront
    - moto.cloudwatch
    - moto.codecommit
    - moto.codepipeline
    - moto.cognitoidentity
    - moto.cognitoidp
    - moto.config
    - moto.core
    - moto.datapipeline
    - moto.datasync
    - moto.dax
    - moto.dms
    - moto.dms
    - moto.ds
    - moto.dynamodb
    - moto.dynamodbstreams
    - moto.ec2
    - moto.ec2.responses
    - moto.ec2instanceconnect
    - moto.ecr
    - moto.ecs
    - moto.efs
    - moto.eks
    - moto.elasticache
    - moto.elasticbeanstalk
    - moto.elastictranscoder
    - moto.elb
    - moto.elbv2
    - moto.emr
    - moto.emrcontainers
    - moto.es
    - moto.events
    - moto.firehose
    - moto.forecast
    - moto.glacier
    - moto.glue
    - moto.guardduty
    - moto.iam
    - moto.instance_metadata
    - moto.iot
    - moto.iotdata
    - moto.kinesis
    - moto.kinesisvideo
    - moto.kinesisvideoarchivedmedia
    - moto.kms
    - moto.logs
    - moto.managedblockchain
    - moto.mediaconnect
    - moto.medialive
    - moto.mediapackage
    - moto.mediastore
    - moto.mediastoredata
    - moto.opsworks
    - moto.organizations
    - moto.packages
    - moto.polly
    - moto.ram
    - moto.rds
    - moto.redshift
    - moto.resourcegroups
    - moto.resourcegroupstaggingapi
    - moto.route53
    - moto.route53resolver
    - moto.s3
    - moto.s3bucket_path
    - moto.s3control
    - moto.sagemaker
    - moto.sdb
    - moto.secretsmanager
    - moto.ses
    - moto.sns
    - moto.sqs
    - moto.ssm
    - moto.ssoadmin
    - moto.stepfunctions
    - moto.sts
    - moto.support
    - moto.swf
    - moto.swf.models
    - moto.timestreamwrite
    - moto.transcribe
    - moto.utilities
    - moto.wafv2
    - moto.xray
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - moto_server --help

about:
  home: http://getmoto.org
  license: Apache-2.0
  summary: A library that allows your python tests to easily mock out the boto library.
  license_family: APACHE
  license_file: LICENSE
  doc_url: http://docs.getmoto.org
  dev_url: https://github.com/spulec/moto

extra:
  recipe-maintainers:
    - jan-janssen
    - johanneskoester
    - mariusvniekerk
    - hajapy
