{% set version = "1.3.10" %}

package:
  name: moto
  version: {{ version }}

source:
  fn: moto-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/m/moto/moto-{{ version }}.tar.gz
  sha256: 92f3ffd6f0dcf5befec9093579180a53fef026c6c7aa30ed6c1ce31c4b00986e

build:
  number: 0
  noarch: python
  entry_points:
    - moto_server = moto.server:main
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - jinja2 >=2.10.1
    - boto >=2.36.0
    - boto3 >=1.9.86
    - botocore >=1.12.86
    - cryptography >=2.3.0
    - requests >=2.5
    - xmltodict
    - six >1.9
    - werkzeug
    - pyyaml
    - pytz
    - python-dateutil >=2.1,<3.0.0
    - python-jose <4.0.0
    - mock
    - docker-py >=2.5.1
    - jsondiff 1.1.2
    - aws-xray-sdk !=0.96,>=0.93
    - responses >=0.9.0
    - idna >=2.5,<2.9
    - cfn-lint
    - flask
    # this is an undeclared dependency!
    - backports.tempfile

test:
  imports:
    - moto
    - moto.acm
    - moto.apigateway
    - moto.autoscaling
    - moto.awslambda
    - moto.batch
    - moto.cloudformation
    - moto.cloudwatch
    - moto.cognitoidentity
    - moto.cognitoidp
    - moto.config
    - moto.core
    - moto.datapipeline
    - moto.dynamodb
    - moto.dynamodb2
    - moto.dynamodbstreams
    - moto.ec2
    - moto.ec2.responses
    - moto.ecr
    - moto.ecs
    - moto.elb
    - moto.elbv2
    - moto.emr
    - moto.events
    - moto.glacier
    - moto.glue
    - moto.iam
    - moto.instance_metadata
    - moto.iot
    - moto.iotdata
    - moto.kinesis
    - moto.kms
    - moto.logs
    - moto.opsworks
    - moto.organizations
    - moto.packages
    - moto.packages.httpretty
    - moto.polly
    - moto.rds
    - moto.rds2
    - moto.redshift
    - moto.resourcegroupstaggingapi
    - moto.route53
    - moto.s3
    - moto.s3bucket_path
    - moto.secretsmanager
    - moto.ses
    - moto.sns
    - moto.sqs
    - moto.ssm
    - moto.sts
    - moto.swf
    - moto.swf.models
    - moto.xray
  commands:
    - moto_server --help

about:
  home: http://getmoto.org
  license: Apache-2.0
  summary: A library that allows your python tests to easily mock out the boto library.
  license_family: APACHE
  license_file: LICENSE
  doc_url: http://docs.getmoto.org
  dev_url: https://github.com/spulec/moto

extra:
  recipe-maintainers:
    - johanneskoester
    - mariusvniekerk
    - hajapy
